config/routes.rb
Rails.application.routes.draw do
  root 'websites#index'
  put '/websites/:id/stop' => 'websites#run', as: 'run_website'
  put '/websites/:id/start' => 'websites#stop', as: 'stop_website'
  resources :websites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/website.rb
class Website < ApplicationRecord
  validates_presence_of :title

  def image
    Docker::Image.get(image_name)
  end

  def pull

  end

  def run
    opts = JSON.parse(run_options)
    container = image.run(run_command, opts)
    puts container.to_s
    self.container_id = container.id
    self.save
  end

  def container
    if running?
      return Docker::Container.get(self.container_id)
    end
    return nil
  end

  def stop
    container = Docker::Container.get(container_id)
    container.stop
    container.delete
    self.container_id = nil
    self.save
  end

  def url
    port_bindings = run_options[:HostConfig][:PortBindings]
    port = ''
    port_bindings.each do |k,v|
      port = v[0]
    end
    return port
  end

  def running?
    if self.container_id.to_s != ''
      return true
    end
    return false
  end

  def stats
    if running?
      return container.stats
    end

    return nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy, :run, :stop]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  def run
    if @website.run
      redirect_to @website, notice: "Started container #{@website.container_id}"
    end
  end

  def stop
    if @website.stop

      redirect_to @website, notice: "Stopped container #{@website.container_id}"
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:title, :image_name, :run_options, :run_command)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docker_helper.rb
module DockerHelper
  def container_exists?(name)

  end
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StageIt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/websites/_form.html.erb
<%= form_for(website) do |f| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image_name %>
    <%= f.text_area :image_name %>
  </div>

  <div>
    <%= f.label :run_command %>
    <%= f.text_field :run_command %>
  </div>

  <div>
    <%= f.label :run_options %>
    <%= f.text_area :run_options %>
  </div>
  <div>
    <code>
    </code>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= javascript_include_tag "jsoneditor" %>

<script type="text/javascript">
function installJsonEditor(tag) {
  var container = document.getElementById(tag);
  var options = {};
  var editor = new JSONEditor(container, options);

  var json = {
    "Array": [1, 2, 3],
    "Boolean": true,
    "Null": null,
    "Number": 123,
    "Object": {"a": "b", "c": "d"},
    "String": "Hello World"
  };
  editor.set(json);
  var json = editor.get();
}
installJsonEditor('website_run_options')
</script>

app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Websites</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image Name</th>
      <th>Running</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.title %></td>
        <td><%= website.image_name %></td>
        <td><%= website.running? ? "🔥" : "🛑"%></td>
        <td><%= link_to 'Show', website , class: 'btn btn-default'%></td>
        <td><%= link_to 'Edit', edit_website_path(website), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %>

app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @website.title %>
</p>

<p>
  <strong>Image name:</strong>
  <%= @website.image_name %>
</p>
<div>
  <p>Stats</p>
  <code>
    <%= @website.stats %>
  </code>
</div>

<%= link_to 'Run', run_website_path(@website), method: :put, class: 'btn btn-success' %>
<%= link_to 'Stop', stop_website_path(@website), method: :put, class: 'btn btn-danger'%>
<br/>
<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>